spring.application.name=ledgerflow

spring.datasource.url=jdbc:postgresql://localhost:5432/ledgerflow
spring.datasource.username=ledgerflow_user
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

management.endpoints.web.exposure.include=health,info